name: gradle buildPlugin

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk

      - name: gradle build
        run: ./gradlew clean buildPlugin
